Use RawConfigParser for Python3
With Python3, the `distutils.config` no longer contains `ConfigParser`, but it does contain `RawConfigParser`.

When using `python setup.py install` in the `/home/user//github/image_registration/` directory, I received the following AttributeError:

```
Traceback (most recent call last):
  File "setup.py", line 29, in <module>
    conf = config.ConfigParser()
AttributeError: module 'distutils.config' has no attribute 'ConfigParser'
```

Changing line 25 of `setup.py` from `conf = config.ConfigParser` to 

```
if sys.version_info[0] >= 3:
    # Python3
    conf = config.RawConfigParser()
else:
    # Python2
    conf = config.ConfigParser()
```

fixes this issue. 

I am **not** sure if `RawConfigParser` has the same robustness as `ConfigParser`, but it solves this issue.